<a href="https://colab.research.google.com/github/ikramtahir24/TP_SQL_Finance_data.csv-/blob/main/tp_sql_db_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

url = "https://raw.githubusercontent.com/ikramtahir24/TP_SQL_Finance_data.csv-/refs/heads/main/Finance_data.csv"
df = pd.read_csv(url)
df.head()

,gender,age,Investment_Avenues,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,...,Duration,Invest_Monitor,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD,Source
0,Female,34,Yes,1,2,5,3,7,6,4,...,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Fixed Returns,Newspapers and Magazines
1,Female,23,Yes,4,3,2,1,5,6,7,...,More than 5 years,Weekly,20%-30%,Mutual Fund,Health Care,Dividend,Better Returns,Safe Investment,High Interest Rates,Financial Consultants
2,Male,30,Yes,3,6,4,2,5,1,7,...,3-5 years,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Tax Benefits,Assured Returns,Fixed Returns,Television
3,Male,22,Yes,2,1,3,7,6,4,5,...,Less than 1 year,Daily,10%-20%,Equity,Retirement Plan,Dividend,Fund Diversification,Tax Incentives,High Interest Rates,Internet
4,Female,24,No,2,1,3,6,4,5,7,...,Less than 1 year,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Risk Free,Internet

In [8]:
import pandas as pd
from pathlib import Path
from google.colab import drive

# Connexion à Google Drive
drive.mount('/content/drive')

# Mise à jour vers un chemin valide détecté dans votre Drive
chemin = Path('/content/drive/MyDrive/Colab Datasets/train.csv')

if not chemin.is_file():
    print("❌ Erreur : Le fichier spécifié n'a pas été trouvé.")
    mydrive_path = Path('/content/drive/MyDrive')
    if mydrive_path.exists():
        print("\nVoici les dossiers/fichiers disponibles à la racine de votre Drive :")
        for item in sorted(mydrive_path.iterdir()):
            if not item.name.startswith('.'):
                print(f" - {item.name}/" if item.is_dir() else f" - {item.name}")
    raise FileNotFoundError(f'Fichier introuvable : {chemin}')
else:
    df = pd.read_csv(chemin)
    display(df.head(10))
    print('Nombre de lignes :', df.shape[0])
    print('Nombre de colonnes :', df.shape[1])

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

Nombre de lignes : 891
Nombre de colonnes : 12

In [10]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('tp_sql.db')

# Importer le DataFrame dans la table "donnees"
df.to_sql('donnees', conn, if_exists='replace', index=False)

# Première requête
resultat = pd.read_sql_query('SELECT * FROM donnees LIMIT 10;', conn)
display(resultat)

# Vérifier le nombre de lignes importées
total = pd.read_sql_query('SELECT COUNT(*) AS total FROM donnees;', conn)
display(total)

conn.close()

# Pour d'autres requêtes, rouvrez la connexion (la cellule ci-dessus la ferme à la fin) :
# conn = sqlite3.connect('tp_sql.db')
# pd.read_sql_query('SELECT * FROM donnees WHERE colonne = "valeur";', conn)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,None,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,None,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,None,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,None,C

   total
0    891

In [12]:
import os
import shutil

# Définir le dossier cible et s'assurer qu'il existe
destination_dir = '/content/drive/MyDrive/TP_SQL_Dataset'
os.makedirs(destination_dir, exist_ok=True)

# Copier le fichier de la base de données
destination_file = os.path.join(destination_dir, 'tp_sql.db')
shutil.copy('tp_sql.db', destination_file)
print(f"Succès ! La base de données a été sauvegardée dans : {destination_file}")

Succès ! La base de données a été sauvegardée dans : /content/drive/MyDrive/TP_SQL_Dataset/tp_sql.db